// Each question has two options (a/b) and an optional MBTI dichotomy tag.
// dim "EI" -> a leans E, b leans I. Same pattern for "SN" (S/N), "TF" (T/F), "JP" (J/P).
// dim: null just means it's a silly one for fun -- it never counts toward the tally.
// Tagged questions are written as ordinary silly would-you-rathers first --
// the personality lean should never be obvious just from reading them.
const QUESTIONS = [
  // Extraversion / Introversion
  { a: "Throw a parade through town with a hundred friends marching behind you", b: "Discover a secret cave only you know how to find", dim: "EI" },
  { a: "Have a superpower that makes every room burst into a dance party", b: "Have a superpower that wraps you in an invisible bubble of silence", dim: "EI" },
  { a: "Win a golden ticket to the world's biggest carnival", b: "Win a golden key to your own private treehouse fortress", dim: "EI" },
  { a: "Lead a marching band through the whole school", b: "Sneak through a hidden tunnel only you know about", dim: "EI" },
  { a: "Host a talent show where the whole town performs together", b: "Build a one-person puppet show just for yourself", dim: "EI" },
  { a: "Be a famous singer performing for a stadium of fans", b: "Be a mysterious painter whose art hangs in museums, but nobody's ever met you", dim: "EI" },
  { a: "Ride to school in a bus packed with friends singing at the top of their lungs", b: "Ride to school in a hot air balloon, just you and the clouds", dim: "EI" },
  { a: "Get a magic megaphone that gathers every kid in the neighborhood to play", b: "Get a magic key that unlocks a hideout no one else can enter", dim: "EI" },
  { a: "Have a birthday wish that fills your backyard with a hundred new friends", b: "Have a birthday wish that gives you a treehouse only you can climb into", dim: "EI" },
  { a: "Be the ringmaster of a circus with a roaring crowd", b: "Be a lighthouse keeper on a quiet, misty island", dim: "EI" },
  { a: "Win a contest by getting the whole cafeteria to cheer your name", b: "Win a contest by solving a puzzle alone in total silence", dim: "EI" },
  { a: "Have a pet dragon that loves flying you over huge cheering crowds", b: "Have a pet owl that only comes out for you in a quiet moonlit forest", dim: "EI" },
  { a: "Get invited to every party in the kingdom", b: "Get the key to a library that's completely empty except for you", dim: "EI" },
  { a: "Be a superhero who fights crime with a whole team by your side", b: "Be a superhero who works alone, unseen, in the shadows", dim: "EI" },
  { a: "Have a magic horn that instantly gathers a crowd to celebrate with you", b: "Have a magic cloak that makes the whole world go quiet around you", dim: "EI" },
  { a: "Explore a new planet with a spaceship full of astronaut friends", b: "Explore a new planet alone in your own tiny rocket", dim: "EI" },
  { a: "Be crowned the loudest cheerleader in the kingdom", b: "Be the quiet archer no one notices until the final shot", dim: "EI" },
  { a: "Get a wish that turns every stranger you meet into an instant friend", b: "Get a wish that turns any crowded room into your own peaceful hideaway", dim: "EI" },
  { a: "Join a pirate crew with a hundred rowdy sailors", b: "Sail a tiny boat alone across a calm, silent sea", dim: "EI" },
  { a: "Have a genie who fills your castle with music and guests every night", b: "Have a genie who guards your castle so no one ever bothers you", dim: "EI" },

  // Sensing / Intuition
  { a: "Get a treasure map with an X marking the exact spot", b: "Get a riddle that hints the treasure could be anywhere in the world", dim: "SN" },
  { a: "Have a pet dragon that's real and sleeps in your backyard", b: "Have a dream where you can imagine a dragon into being anything you want", dim: "SN" },
  { a: "Own a book of true facts about every animal that ever lived", b: "Own a blank book where you get to invent brand new animals nobody's seen", dim: "SN" },
  { a: "Build your fort using a blueprint that shows every exact step", b: "Build your fort by imagining it first and inventing it as you go", dim: "SN" },
  { a: "Have a crystal ball that shows exactly what happens tomorrow", b: "Have a crystal ball that only shows swirling shapes for you to guess at", dim: "SN" },
  { a: "Visit a real castle you can touch and explore today", b: "Design a castle that's never existed, floating somewhere in your imagination", dim: "SN" },
  { a: "Learn a spell by copying each step exactly from a spellbook", b: "Invent your own brand new spell that's never been cast before", dim: "SN" },
  { a: "Get a telescope that shows real stars exactly as they are", b: "Get a telescope that shows whatever your imagination dreams up in the sky", dim: "SN" },
  { a: "Solve a maze using a map that shows the one true path", b: "Solve a maze by imagining new shortcuts nobody's tried", dim: "SN" },
  { a: "Have a robot that tells you exactly how machines work", b: "Have a robot that only speaks in riddles about the future", dim: "SN" },
  { a: "Study a dinosaur bone that's real and dug up from the ground", b: "Imagine a brand new dinosaur that's never existed and give it powers", dim: "SN" },
  { a: "Get a map of the forest showing every real path", b: "Wander into the forest and see what magic you discover", dim: "SN" },
  { a: "Own a potion book with recipes that always work the same way", b: "Mix up your own mystery potion and see what wild thing happens", dim: "SN" },
  { a: "Watch a documentary about real sharks in the deep ocean", b: "Watch a movie about legendary sea monsters no one's ever proven exist", dim: "SN" },
  { a: "Get a globe that shows every real country on Earth", b: "Get a map to a magical land that only appears in stories", dim: "SN" },
  { a: "Fix a broken clock using the instructions in the manual", b: "Take the clock apart and invent a wild new way to fix it", dim: "SN" },
  { a: "Collect real rocks and learn their exact scientific names", b: "Collect rocks and imagine each one holds a hidden magical power", dim: "SN" },
  { a: "Retell a legend exactly the way the storyteller told it", b: "Retell the legend your own way, with a brand new twist ending", dim: "SN" },
  { a: "Plant a garden using exact instructions for what will grow", b: "Plant mystery seeds and imagine what strange plant might grow", dim: "SN" },
  { a: "Check the weather report before planning a picnic", b: "Just go with your gut feeling about whether it'll rain", dim: "SN" },

  // Thinking / Feeling
  { a: "As a knight, win the joust fair and square", b: "As a knight, let the nervous new recruit win his very first joust", dim: "TF" },
  { a: "Be a dragon-riding judge who always makes the fair call, even if your best friend loses", b: "Be a dragon-riding judge who bends the rules a little to keep your friend smiling", dim: "TF" },
  { a: "As a wizard, tell your apprentice their spell was cast wrong so they can fix it", b: "As a wizard, tell your apprentice the spell was perfect so they feel proud", dim: "TF" },
  { a: "Be the referee who calls every foul, even against your own team", b: "Be the referee who lets a few fouls slide to keep the game friendly", dim: "TF" },
  { a: "Be known across the kingdom as the fairest ruler", b: "Be known across the kingdom as the kindest ruler", dim: "TF" },
  { a: "Pick your quest team based purely on who has the best skills", b: "Pick your quest team so nobody feels left out of the adventure", dim: "TF" },
  { a: "Win the treasure by being first to solve the riddle", b: "Split the treasure evenly so nobody's upset, even if you solved it first", dim: "TF" },
  { a: "Tell your best friend their potion recipe has a mistake, so they can fix it before the contest", b: "Tell them it's perfect so they feel confident walking into the contest", dim: "TF" },
  { a: "Choose your project partner because they're the best at spellcasting", b: "Choose your project partner because they're the most fun to adventure with", dim: "TF" },
  { a: "Be the friend dragons call when they need a tricky puzzle solved", b: "Be the friend dragons call when they just need someone to listen", dim: "TF" },
  { a: "Point out when the pirate captain breaks the crew's code, even if he's your friend", b: "Look the other way to keep the peace on the ship", dim: "TF" },
  { a: "Settle a dispute between two knights by figuring out who's actually right", b: "Settle it by finding a way that makes both knights feel better", dim: "TF" },
  { a: "Give your apprentice wizard totally honest feedback, even if it stings a little", b: "Give gentle feedback, even if it's not the whole truth", dim: "TF" },
  { a: "Finish the spell your way because it's the more correct one", b: "Finish it the group's way so nobody in the coven is upset", dim: "TF" },
  { a: "Be the castle advisor famous for being brilliantly logical", b: "Be the castle advisor famous for being deeply caring", dim: "TF" },
  { a: "Choose the smartest battle plan even if your knight disagrees", b: "Choose the plan that keeps your knight feeling brave and happy", dim: "TF" },
  { a: "Referee the dragon race by the book, no exceptions", b: "Referee the dragon race with a little extra kindness for the underdog", dim: "TF" },
  { a: "Explain to the young apprentice exactly why their spell is wrong", b: "Find a gentle way to help them feel okay about the mistake", dim: "TF" },
  { a: "Keep your vote for the kingdom's feast because it's the fairest pick", b: "Change your vote because your friend really wants the other feast", dim: "TF" },
  { a: "Win the debate at the round table, even if it makes things a little awkward", b: "Drop your point at the round table so everyone can feast happily", dim: "TF" },

  // Judging / Perceiving
  { a: "Have a magic map that reveals your whole day's adventure before it starts", b: "Have a magic map that only reveals the very next step, one surprise at a time", dim: "JP" },
  { a: "Pack your adventurer's bag the night before the quest", b: "Grab whatever's nearby and dash off when the quest calls", dim: "JP" },
  { a: "Follow a strict schedule of spells to practice every day", b: "Practice whatever spell feels fun in the moment", dim: "JP" },
  { a: "Finish training for the tournament weeks before it starts", b: "Cram all your training into the exciting night before", dim: "JP" },
  { a: "Go on a quest with every single day mapped out in advance", b: "Go on a quest and decide where to explore as you go", dim: "JP" },
  { a: "Keep your dragon's stable perfectly organized every morning", b: "Let your dragon's toys and treasure pile up in a fun jumble", dim: "JP" },
  { a: "Always know exactly which monster you'll battle next", b: "Love not knowing which monster might surprise you next", dim: "JP" },
  { a: "Choose your knight costume for the festival weeks in advance", b: "Decide your knight costume the night before the festival", dim: "JP" },
  { a: "Finish exploring one cave completely before starting the next", b: "Hop between five different caves all in one afternoon", dim: "JP" },
  { a: "Have a clear checklist of spells to master today", b: "Have an open day to just see what magic happens", dim: "JP" },
  { a: "Know your whole week of quests by Monday", b: "Figure out your quests as each day comes", dim: "JP" },
  { a: "Cross off each dragon egg on your to-hatch list one by one", b: "Jump around hatching whichever egg feels exciting in the moment", dim: "JP" },
  { a: "Show up to the wizard council right on time, every time", b: "Show up whenever feels right, spell in hand", dim: "JP" },
  { a: "Read the final page of the prophecy first so you know how it ends", b: "Let the prophecy surprise you the whole way through", dim: "JP" },
  { a: "Plan out your castle completely before laying the first stone", b: "Start building and see what the castle turns into", dim: "JP" },
  { a: "Stick to the quest plan even when a more exciting path appears", b: "Drop the plan the second a more exciting path appears", dim: "JP" },
  { a: "Keep a tidy, organized potion shelf", b: "Keep a potion shelf full of fun clutter only you understand", dim: "JP" },
  { a: "Pick your ice cream flavor from the enchanted parlor the second you walk in", b: "Taste a few magical samples before deciding", dim: "JP" },
  { a: "Decide your team's battle strategy the night before and stick to it", b: "Make up your battle strategy on the spot as the fight unfolds", dim: "JP" },
  { a: "Have your spellbook color-coded and alphabetized", b: "Have your spellbook a fun, mysterious mess only you can navigate", dim: "JP" },

  // Just for fun (not scored)
  { a: "Have spaghetti for hair", b: "Have marshmallows for teeth", dim: null },
  { a: "Be able to talk to animals", b: "Be able to talk to plants", dim: null },
  { a: "Have a pet dragon the size of a cat", b: "Have a pet elephant the size of a mouse", dim: null },
  { a: "Eat pizza with syrup on it", b: "Eat ice cream with ketchup on it", dim: null },
  { a: "Be able to fly like a bird", b: "Be able to breathe underwater like a fish", dim: null },
  { a: "Have hiccups that sound like a duck", b: "Have a sneeze that sounds like a trumpet", dim: null },
  { a: "Live in a treehouse", b: "Live in an underground fort", dim: null },
  { a: "Have shoes that never untie", b: "Have socks that never get holes", dim: null },
  { a: "Ride a roller coaster made of candy", b: "Ride a water slide made of jelly", dim: null },
  { a: "Have a hundred jellybeans", b: "Have one giant chocolate bar", dim: null },
  { a: "Turn invisible whenever you sneeze", b: "Freeze in place whenever you laugh", dim: null },
  { a: "Wear a raincoat made of bubble wrap", b: "Wear rain boots made of jelly", dim: null },
  { a: "Have a robot best friend", b: "Have a dinosaur best friend", dim: null },
  { a: "Be the size of a giant for a day", b: "Be the size of an ant for a day", dim: null },
  { a: "Have a slide instead of stairs at home", b: "Have a trampoline instead of a floor in your room", dim: null },
  { a: "Only be able to whisper", b: "Only be able to shout", dim: null },
  { a: "Have grass that's always purple", b: "Have rain that's always warm", dim: null },
  { a: "Eat one weird bug for a million dollars", b: "Skip dessert for a whole year for a million dollars", dim: null },
  { a: "Have a pet that can juggle", b: "Have a pet that can skateboard", dim: null },
  { a: "Wake up as your favorite cartoon character for a day", b: "Wake up as your favorite animal for a day", dim: null },
];
