// Each question has two options (a/b) and an optional MBTI dichotomy tag.
// dim "EI" -> a leans E, b leans I. Same pattern for "SN" (S/N), "TF" (T/F), "JP" (J/P).
// dim: null just means it's a silly one for fun -- it never counts toward the tally.
const QUESTIONS = [
  // Extraversion / Introversion
  { a: "Throw a huge birthday party with your whole class", b: "Have a cozy sleepover with just your best friend", dim: "EI" },
  { a: "Be the one inviting everyone to play a game", b: "Quietly build the best blanket fort all by yourself", dim: "EI" },
  { a: "Tell a funny story out loud to the whole lunch table", b: "Write the story down in your own secret notebook", dim: "EI" },
  { a: "Cheer loudly from the front row", b: "Watch happily from a comfy spot in the back", dim: "EI" },
  { a: "Have recess be one giant group game", b: "Have recess be free time to do your own thing", dim: "EI" },
  { a: "Share every idea the second you think of it", b: "Think it over quietly before you say anything", dim: "EI" },
  { a: "Work on a class project with a big team", b: "Handle the whole project yourself in your room", dim: "EI" },
  { a: "Spend a rainy day at a friend's noisy house party", b: "Spend a rainy day curled up alone with a good book", dim: "EI" },
  { a: "Make new friends by talking to everyone at a new school", b: "Make one close friend slowly over time", dim: "EI" },
  { a: "Give a speech in front of the whole school", b: "Help behind the scenes where no one sees you", dim: "EI" },
  { a: "Celebrate winning with a huge group high-five", b: "Celebrate winning with a quiet fist bump", dim: "EI" },
  { a: "Sit at the busiest, loudest lunch table", b: "Sit at a small quiet table with one or two friends", dim: "EI" },
  { a: "Answer questions out loud in class", b: "Write your answers down and turn them in", dim: "EI" },
  { a: "Go to a carnival packed with people and noise", b: "Go on a quiet nature walk with just you", dim: "EI" },
  { a: "Recharge after a long day by hanging out with friends", b: "Recharge after a long day with quiet time alone", dim: "EI" },
  { a: "Be the loudest cheerleader for your team", b: "Be the calm one who quietly believes in your team", dim: "EI" },
  { a: "Show your artwork to the whole class at once", b: "Show your artwork to one friend first", dim: "EI" },
  { a: "Plan a group adventure with lots of friends", b: "Plan a quiet adventure just for you", dim: "EI" },
  { a: "Talk through a problem out loud with someone", b: "Think through a problem quietly in your head", dim: "EI" },
  { a: "Join a big team sport", b: "Practice a solo sport or hobby", dim: "EI" },

  // Sensing / Intuition
  { a: "Follow a recipe exactly to bake perfect cookies", b: "Toss in random ingredients to invent a brand new treat", dim: "SN" },
  { a: "Learn a magic trick by watching it step by step", b: "Make up your own magic trick from scratch", dim: "SN" },
  { a: "Explore a cave using a detailed map", b: "Wander into a cave and see what you discover", dim: "SN" },
  { a: "Build a Lego set by following the instructions", b: "Dump out the pieces and build something totally new", dim: "SN" },
  { a: "Know exactly how a magic trick works", b: "Enjoy the mystery and never find out", dim: "SN" },
  { a: "Describe exactly what you see in a cloud", b: "Imagine it's a dragon flying to another galaxy", dim: "SN" },
  { a: "Visit a real famous castle", b: "Design your own imaginary castle that's never existed", dim: "SN" },
  { a: "Memorize real facts about every dinosaur", b: "Invent a brand new dinosaur nobody's ever seen", dim: "SN" },
  { a: "Fix something using the instructions in the manual", b: "Figure it out yourself by trial and error", dim: "SN" },
  { a: "Have a pet that's a real animal you take care of every day", b: "Have a make-believe pet with any power you imagine", dim: "SN" },
  { a: "Learn history by reading exactly what happened", b: "Imagine what might have happened instead", dim: "SN" },
  { a: "Draw something you can actually see in front of you", b: "Draw something that only exists in your imagination", dim: "SN" },
  { a: "Play a board game exactly by the rulebook", b: "Make up your own house rules as you go", dim: "SN" },
  { a: "Take a class that teaches real-world skills like cooking", b: "Take a class that teaches you to invent new worlds through stories", dim: "SN" },
  { a: "Solve a puzzle by remembering the exact steps that worked before", b: "Solve a puzzle by trying a totally new idea", dim: "SN" },
  { a: "Watch a documentary about real space missions", b: "Watch a movie about aliens from a made-up galaxy", dim: "SN" },
  { a: "Organize your rock collection by real facts like size and color", b: "Imagine each rock has its own secret magical power", dim: "SN" },
  { a: "Retell a story exactly the way you heard it", b: "Retell a story your own new way, with a twist", dim: "SN" },
  { a: "Plant a garden by following exact planting instructions", b: "Plant a garden and imagine what surprises might grow", dim: "SN" },
  { a: "Trust what you can see, touch, and test", b: "Trust your gut feeling about how things might turn out", dim: "SN" },

  // Thinking / Feeling
  { a: "Make the fair call even if your friend gets upset", b: "Bend the rule a little to keep everyone happy", dim: "TF" },
  { a: "Win a game by playing your very best", b: "Let a little kid win so they feel good", dim: "TF" },
  { a: "Give a friend honest feedback that might sting a little", b: "Give a kind little fib to make them smile", dim: "TF" },
  { a: "Solve an argument by figuring out who's actually right", b: "Solve an argument by finding what makes everyone feel better", dim: "TF" },
  { a: "Be known as the fairest kid in school", b: "Be known as the kindest kid in school", dim: "TF" },
  { a: "Pick teams using strict rules like height or skill", b: "Pick teams so nobody feels left out", dim: "TF" },
  { a: "Win a prize for the smartest answer", b: "Win a prize for being the best friend", dim: "TF" },
  { a: "Tell a friend their drawing has mistakes so they can fix it", b: "Tell them it's perfect so they feel proud", dim: "TF" },
  { a: "Make big choices with your head", b: "Make big choices with your heart", dim: "TF" },
  { a: "Be a judge who always follows the rulebook", b: "Be a judge who listens to everyone's feelings first", dim: "TF" },
  { a: "Point out when a rule gets broken, even for a friend", b: "Look the other way to keep the peace", dim: "TF" },
  { a: "Decide a class vote by counting votes exactly", b: "Decide a class vote by checking how everyone truly feels", dim: "TF" },
  { a: "Give advice that's totally honest, even if it stings", b: "Give advice that's gentle, even if it's not the full truth", dim: "TF" },
  { a: "Finish an assignment your way because it's more correct", b: "Finish it the group's way so nobody's upset", dim: "TF" },
  { a: "Be praised for being super logical", b: "Be praised for being super caring", dim: "TF" },
  { a: "Choose the smartest plan even if a friend disagrees", b: "Choose the plan that keeps your friend happy", dim: "TF" },
  { a: "Referee a game by the book, no exceptions", b: "Referee a game with a little extra kindness", dim: "TF" },
  { a: "Explain exactly why someone is wrong", b: "Find a gentle way to help them feel okay about it", dim: "TF" },
  { a: "Stick to a decision because it's the right one", b: "Change your decision because someone's feelings changed", dim: "TF" },
  { a: "Care most about being right", b: "Care most about everyone getting along", dim: "TF" },

  // Judging / Perceiving
  { a: "Plan your whole birthday party weeks ahead", b: "Decide what to do the morning of your birthday", dim: "JP" },
  { a: "Have your backpack perfectly organized every day", b: "Dig through a fun messy pile to find your stuff", dim: "JP" },
  { a: "Follow a strict daily schedule", b: "Wake up and see what the day brings", dim: "JP" },
  { a: "Finish your homework the day it's assigned", b: "Save it for the last exciting minute", dim: "JP" },
  { a: "Go on a trip with every single day planned out", b: "Go on a trip and decide as you go", dim: "JP" },
  { a: "Make your bed and tidy your room every morning", b: "Leave it messy and jump straight into fun", dim: "JP" },
  { a: "Always know exactly what's happening next", b: "Love being surprised by a change of plans", dim: "JP" },
  { a: "Pack your bag the night before", b: "Grab whatever you can find on your way out", dim: "JP" },
  { a: "Finish one game completely before starting a new one", b: "Bounce between five games at once", dim: "JP" },
  { a: "Have a clear checklist for the day", b: "Have an open day with no plan at all", dim: "JP" },
  { a: "Pick your Halloween costume weeks in advance", b: "Decide your costume the night before", dim: "JP" },
  { a: "Keep your toys sorted into neat labeled bins", b: "Keep your toys in one big fun jumble", dim: "JP" },
  { a: "Know your weekend plans by Monday", b: "Figure out your weekend plans on Saturday morning", dim: "JP" },
  { a: "Cross things off a to-do list one by one", b: "Jump around to whatever feels fun in the moment", dim: "JP" },
  { a: "Show up right on time, every time", b: "Show up whenever feels right", dim: "JP" },
  { a: "Read the last page of a book first so you know what happens", b: "Let the story surprise you the whole way through", dim: "JP" },
  { a: "Plan out a fort completely before you build it", b: "Start building and see what the fort turns into", dim: "JP" },
  { a: "Stick to the plan even if something more fun comes up", b: "Drop the plan the second something more fun comes up", dim: "JP" },
  { a: "Keep a tidy, organized desk", b: "Keep a desk full of fun clutter you understand", dim: "JP" },
  { a: "Decide now so it's settled", b: "Keep your options open as long as possible", dim: "JP" },

  // Just for fun (not scored)
  { a: "Have spaghetti for hair", b: "Have marshmallows for teeth", dim: null },
  { a: "Be able to talk to animals", b: "Be able to talk to plants", dim: null },
  { a: "Have a pet dragon the size of a cat", b: "Have a pet elephant the size of a mouse", dim: null },
  { a: "Eat pizza with syrup on it", b: "Eat ice cream with ketchup on it", dim: null },
  { a: "Be able to fly like a bird", b: "Be able to breathe underwater like a fish", dim: null },
  { a: "Have hiccups that sound like a duck", b: "Have a sneeze that sounds like a trumpet", dim: null },
  { a: "Live in a treehouse", b: "Live in an underground fort", dim: null },
  { a: "Have shoes that never untie", b: "Have socks that never get holes", dim: null },
  { a: "Ride a roller coaster made of candy", b: "Ride a water slide made of jelly", dim: null },
  { a: "Have a hundred jellybeans", b: "Have one giant chocolate bar", dim: null },
  { a: "Turn invisible whenever you sneeze", b: "Freeze in place whenever you laugh", dim: null },
  { a: "Wear a raincoat made of bubble wrap", b: "Wear rain boots made of jelly", dim: null },
  { a: "Have a robot best friend", b: "Have a dinosaur best friend", dim: null },
  { a: "Be the size of a giant for a day", b: "Be the size of an ant for a day", dim: null },
  { a: "Have a slide instead of stairs at home", b: "Have a trampoline instead of a floor in your room", dim: null },
  { a: "Only be able to whisper", b: "Only be able to shout", dim: null },
  { a: "Have grass that's always purple", b: "Have rain that's always warm", dim: null },
  { a: "Eat one weird bug for a million dollars", b: "Skip dessert for a whole year for a million dollars", dim: null },
  { a: "Have a pet that can juggle", b: "Have a pet that can skateboard", dim: null },
  { a: "Wake up as your favorite cartoon character for a day", b: "Wake up as your favorite animal for a day", dim: null },
];
